{"name": "Проверка авторизации курьера с неправильно указанным логином", "status": "passed", "description": "Проверяем, что при указании неверного логина, но правильного пароля, невозможно авторизоваться в системе", "start": 1725467505794, "stop": 1725467506012, "uuid": "d86e41ef-8e97-4771-841e-f0f2aae80ce2", "historyId": "f72318abc1952b198941a917d4776aa0", "testCaseId": "f72318abc1952b198941a917d4776aa0", "fullName": "tests.test_login_courier.TestLoginCourier#test_courier_login_with_wrong_login", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "DESKTOP-VOBQH1U"}, {"name": "thread", "value": "3632-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}]}